name: Release
on:
  release:
    types:
      - created

jobs:
  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: fix plugin.init
        run:  sed -i '' "s/plugin\.init(dir, forgeConfig);/if(plugin.init) plugin.init(dir, forgeConfig);/g" ./node_modules/@electron-forge/core/dist/util/plugin-interface.js
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  publish_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: fix plugin.init
        run:  sed -i '' "s/plugin\.init(dir, forgeConfig);/if(plugin.init) plugin.init(dir, forgeConfig);/g" ./node_modules/@electron-forge/core/dist/util/plugin-interface.js
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
